workflows:
  android-workflow:
    name: Android Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: 3.38.9
      groups:
        - google_play # keystore credentials
    scripts:
      - name: Get dependencies
        script: |
          cd apps/flutter_client
          flutter pub get
      - name: Build Android Release
        script: |
          cd apps/flutter_client
          flutter build apk --release
    artifacts:
      - apps/flutter_client/build/**/outputs/**/*.apk
      - apps/flutter_client/build/**/outputs/**/mapping.txt
      - apps/flutter_client/flutter_drive.log

  windows-workflow:
    name: Windows Release
    max_build_duration: 120
    instance_type: windows_x2
    environment:
      flutter: 3.38.9
    scripts:
      - name: Get dependencies
        script: |
          cd apps/flutter_client
          flutter pub get
      - name: Build Windows Release
        script: |
          cd apps/flutter_client
          flutter build windows --release
    artifacts:
      - apps/flutter_client/build/windows/runner/Release/*.exe

  ios-workflow:
    name: iOS TestFlight Release
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: "popcorn"
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.popcorn.flutterClient"
    scripts:
      - name: Set up Keychain & Fetch Signing Files
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Get dependencies
        script: flutter pub get
      - name: Build IPA for TestFlight
        script: |
          # The --export-options-plist is generated automatically by the 'use-profiles' script above
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  macos-workflow:
    name: macOS Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: 3.38.9
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: |
          cd apps/flutter_client
          flutter pub get
      - name: Install Pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build macOS Release
        script: |
          cd apps/flutter_client
          flutter build macos --release
    artifacts:
      - apps/flutter_client/build/macos/Build/Products/Release/*.app
      - apps/flutter_client/flutter_drive.log
